name: flutter_web_deshboard
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  charts_flutter_new: ^0.12.0
  data_table_2: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
